ErrorObject: !include types/error_object.raml
OkObject: !include types/ok_object.raml
UserSession: !include types/user_session.raml
Product: !include types/product.raml
ProductCategory: !include types/product_category.raml
ProductImage: !include types/product_image.raml
User: !include types/user.raml
Customer: !include types/customer.raml
LineItem: !include types/order/line_item.raml
OrderAmount: !include types/order/amount.raml
Order: !include types/order.raml
OrderInDetail: !include types/order_in_detail.raml
MerchantDomain: !include types/merchant/domain.raml
MerchantSocialMediaSettings: !include types/merchant/social_media_settings.raml
MerchantPaymentSettings: !include types/merchant/payment_settings.raml
MerchantTaxSettings: !include types/merchant/tax_settings.raml
MerchantShippingSettings: !include types/merchant/shipping_settings.raml
Merchant: !include types/merchant.raml
Notification: !include types/notification.raml
Pagination: !include types/pagination.raml
Page: !include types/page.raml
