type: object
properties:
  error?:
    type: boolean
    description: always be true
    example: true
  code?:
    type: string
    description: code of error
    example: client_auth_fail_exception
  message?:
    type: string
    description: error message
    example: Checksum is not matched
