type: object
properties:
  user: User
  country: string
  domain: MerchantDomain
  name: string
  address: string
  published: boolean
  cover_image_url: string
  notifications_count: number
  notification_email: string
  description: string
  social_media_settings: MerchantSocialMediaSettings
  payment_settings: MerchantPaymentSettings
  tax_settings: MerchantTaxSettings
  shipping_settings: MerchantShippingSettings
  version: string
  id: number
