type: object
properties:
  id?: number
  name?: string
  price?: number
  maximum_retail_price?: number
  description?: string
  stock?: number
  product_url?: string
  cover_image?: ProductImage
  category?: ProductCategory
  images?: ProductImage[]
