is: [ session_secured ]
get:
  queryParameters:
    timestamp:
      type: number
      description: "current timestamp"
      example: 1318996912
  is: [ pagination ]
  description: |
    Get notifications.
    pages => 18
  responses:
    200:
      body:
        application/json:
          type: object
          properties:
            notifications?: Notification[]
            pagination: Pagination
/{notification_id}:
  is: [ session_secured ]
  queryParameters:
    notify_type:
      type: string
      description: "system or order_record"
      example: 'system'
  uriParameters:
    notification_id:
      type: number
      description: "Notification id"
      example: 123
  get:
    description: |
      Get notification in detail.
      pages => 18
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              notification?: Notification
