put:
  description: |
    Update password
    pages => 22
  queryParameters:
    merchant[old_password]:
      type: string
      required: true
    merchant[new_password]:
      type: string
      required: true
    merchant[new_password_confirmation]:
      type: string
      required: true
  responses:
    200: !include ../../includes/respond_merchant.raml


