/push-notification: !include ./settings_push_notification.raml
/payments: !include ./settings_payments.raml
/social-media: !include ./settings_social_media.raml
/taxes: !include ./settings_taxes.raml
/shipping: !include ./settings_shipping.raml
/domain: !include ./settings_domain.raml
