put:
  description: |
    Update tax fields of merchant.
    page => 16
  queryParameters:
    setting[sales]:
      type: number
      required: false
      example: 1
    setting[vat]:
      type: number
      required: false
      example: 1
    setting[service]:
      type: number
      required: false
      example: 1
    setting[excise]:
      type: number
      required: false
      example: 1
