is: [ session_secured ]
put:
  description: |
    Update shipping fields of merchant.
    page => 17
  queryParameters:
    settings[fee]:
      type: number
      required: false
      example: 1
    settings[free_enabled]:
      type: boolean
      required: false
    settings[minimum_totoal_for_free_shipping]:
      type: number
      required: false
      example: 1
