description: |
  Update merchant profile.
  page => 13
queryParameters:
  merchant[first_name]:
    type: string
    required: true
    example: 'Mars'
  merchant[last_name]:
    type: string
    required: true
    example: 'Chen'
  merchant[name]: # TODO: q on zeplin 13
    type: string
    required: true
    example: "abc store"
  merchant[email]: # TODO: q on zeplin 13
    type: string
    required: true
    example: "abc@abc.com"
  merchant[phone]: # TODO: q on zeplin 13
    type: string
    required: false
    example: "12345678"
  merchant[address][street_address]:
    type: string
    required: true
    example: '9 Cheong Wan Road'
  merchant[address][city]:
    type: string
    required: true
    example: 'Hung Hom'
  merchant[address][state]:
    type: string
    required: true
    example: 'Kowloon city'
  merchant[address][country]:
    type: string
    required: true
    example: 'HK'
  merchant[address][zip_code]:
    type: string
    required: true
    example: '110001'
  merchant[description]: # TODO: q on zeplin 13
    type: string
    required: false
    example: "abcabanc"
  merchant[notification_email]:
    type: string
    required: false
responses:
  200: !include ../../includes/respond_merchant.raml
