headers:
  SHOPMATIC_CS:
    description: checksum
    type: string
    required: true
    example: '5xrubygogogo'
  SHOPMATIC_UUID:
    description: mobile uuid
    type: string
    required: false
  SHOPMATIC_TS:
    description: timestamp
    type: integer
    required: false
  Accept:
    description: api versioning
    type: string
    required: false
    example: application/vnd.shopmatic.v1
responses:
  401:
    body:
      application/json:
        type: ErrorObject
