queryParameters:
  product[name]:
    type: string
    required: true
    example: "product name #1"
  product[price]:
    type: number
    required: true
    example: 123.123
  product[list_price]:
    type: number
    required: false
    example: 123.123
  product[stock_sum]:
    type: number
    required: true
    example: 123
  product[description]:
    type: string
    required: false
    example: "description"
  product[maximum_retail_price]:
    type: number
    required: false
    example: 123.123
    description: "MRP"
  product[category_name]:
    type: string
    required: false
    example: "Bag"
  product[images]:
    type: string
    description: |
      JSON format as following
      ```
      [
        { "lq_img_url": "https://i.imgur.com/1iepWJ3.jpg",
          "hq_img_url": "https://i.imgur.com/1iepWJ3.jpg"
        },
        { "lq_img_url": "https://i.imgur.com/1iepWJ3.jpg",
          "hq_img_url": "https://i.imgur.com/1iepWJ3.jpg"
        },
        { "lq_img_url": "https://i.imgur.com/1iepWJ3.jpg",
          "hq_img_url": "https://i.imgur.com/1iepWJ3.jpg"
        },
        { "lq_img_url": "https://i.imgur.com/1iepWJ3.jpg",
          "hq_img_url": "https://i.imgur.com/1iepWJ3.jpg"
        }
      ]
      ```
    required: true
    example: '[{"lq_img_url":"https://i.imgur.com/1iepWJ3.jpg","hq_img_url":"https://i.imgur.com/1iepWJ3.jpg"}]'
