is: [ session_secured ]
put: !include merchant/update.raml
get: !include merchant/show.raml
post: !include merchant/create.raml
/with-products: !include merchant/with_products.raml
/publish: !include merchant/publish.raml
/settings: !include merchant/settings.raml
/notifications: !include merchant/notifications.raml
/password: !include merchant/password.raml
