is: [ session_secured ]
get:
  is: [ pagination ]
  description: |
    Get all orders.
    pages => 11b
  responses:
    200: !include ../includes/respond_orders.raml
/unshipped:
  get:
    is: [ pagination, session_secured ]
    description: |
      Get unshipped orders.
      pages => 11b
    responses:
      200: !include ../includes/respond_orders.raml
/{order_code}:
  is: [ session_secured ]
  uriParameters:
    order_code:
      type: string
      description: "Order code"
      example: abcde
  get:
    description: |
      Get unshipped orders.
      pages => 11d
    responses:
      200: !include ../includes/respond_order_in_detail.raml
  /note:
    is: [ session_secured ]
    put:
      description: |
        Update order note.
        page => 11d
      queryParameters:
        order[note]:
          type: string
          required: true
          example: "Order note"
      responses:
        200: !include ../includes/respond_order.raml
  /shipped:
    is: [ session_secured ]
    put:
      description: |
        Change order status to shipped.
        pages => 11d
      responses:
        200: !include ../includes/respond_order.raml
  /unshipped:
    is: [ session_secured ]
    put:
      description: |
        Change order status to unshipped.
        pages => 11d
      responses:
        200: !include ../includes/respond_order.raml
  /cancelled:
    is: [ session_secured ]
    put:
      description: |
        Change order status to canceled.
        pages => 11d
      responses:
        200: !include ../includes/respond_order.raml
  /delivered:
    is: [ session_secured ]
    put:
      description: |
        Change order status to delivered.
        pages => 11d
      responses:
        200: !include ../includes/respond_order.raml
