get:
  description: Get All Pages
  responses:
    200:
      body:
        application/json:
          type: object
          properties:
            pages?: Page[]

/{pageName}:
  is: [ session_secured ]
  uriParameters:
    pageName:
      type: string
      description: Lowercase Page Name, space replaced by hyphen
      example: all-products
  get:
    description: Show Site page
  put:
    description: Update Site page
    body:
      application/json:
        type: object
        properties:
          page: Page
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              page: Page
