post:
  description: user login by email
  queryParameters:
    user[email]:
      type: string
      required: true
      example: 'ilake@5xruby.tw'
  responses:
    200: !include ../includes/respond_ok.raml
