/email:
  post:
    description: |
      User login by email.
      Same user will have multiple tokens, and these tokens will not to be expired.
    queryParameters:
      user[email]:
        type: string
        required: true
        example: 'ilake@5xruby.tw'
      user[password]:
        type: string
        required: true
        example: 'password'

    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              user_session?: UserSession
              merchant?: Merchant

/facebook:
  post:
    description: |
      User login by facebook.
      Same user will have multiple tokens, and these tokens will not to be expired.
    queryParameters:
      user[email]:
        type: string
        required: true
        example: 'ilake@5xruby.tw'
      user[uid]:
        type: string
        required: true
        example: '123456'
      user[access_token]:
        type: string
        required: true
        example: '123456'

    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              user_session?: UserSession
              merchant?: Merchant

/googleplus:
  post:
    description: |
      User login by Google.
      Same user will have multiple tokens, and these tokens will not to be expired.
    queryParameters:
      user[email]:
        type: string
        required: true
        example: 'ilake@5xruby.tw'
      user[uid]:
        type: string
        required: true
        example: '123456'
      user[access_token]:
        type: string
        required: true
        example: '123456'

    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              user_session?: UserSession
              merchant?: Merchant
delete:
  description: |
    Logout
    pages => 12
  queryParameters:
    user_token: string
  responses:
    200: !include ../includes/respond_ok.raml
