body:
  application/json:
    type: object
    properties:
      url:
        type: string
        description: paypal isu onboarding url
        example: https://www.sandbox.paypal.com/SG/merchantsignup/partner/onboardingentry?token=TOKEN_VALUE=&context_token=CONTEXT_TOKEN_VALUE
